=== AngelAcedo12/LMSGI-2223/Bloque1/Tema2/Boletines/2.5/01.temperatura.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="registro_temperatura">

        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="provincia" type="xsd:string" />
                <xsd:element name="fecha" type="xsd:date" />
                <xsd:element name="temperatura_minima" type="xsd:integer" />
                <xsd:element name="temperatura_maxima" type="xsd:integer" />
                <xsd:element name="incidencias" type="tipo_incidencias" />

            </xsd:sequence>
        </xsd:complexType>

    </xsd:element>

    <xsd:complexType name="tipo_incidencias">
        <xsd:sequence>
            <xsd:element name="incidencia"></xsd:element>
        </xsd:sequence>
    </xsd:complexType>


    <xsd:simpleType name="tipo_att_clima">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="frio" />
            <xsd:enumeration value="nieve" />
            <xsd:enumeration value="lluvia" />
            <xsd:enumeration value="calor" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="tipo_att_severidad">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="alta" />
            <xsd:enumeration value="media" />
            <xsd:enumeration value="baja" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:element name="incidencia">
        <xsd:complexType>
            <xsd:simpleContent>
                <xsd:extension base="longitudMaxima">
                    <xsd:attribute name="prodid" type="xsd:string" use="optional" />
                </xsd:extension>
            </xsd:simpleContent>
        </xsd:complexType>
    </xsd:element>


</xsd:schema>

=== AngelAcedo12/LMSGI-2223/Bloque1/Tema2/Boletines/2.5/01.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
    Genera un esquema XSD para validar el siguiente documento XML que contiene un registro de temperaturas con las siguientes condiciones:
 
* El elemento principal contiene un registro de temperaturas con el nombre de la provincia, fecha del registro, la temperatura mínima y maxima y una relacioón de incidencias.
* La fecha de registro debe ser uan fecha válida.
* La temperatura mínima no debe ser inferior a -50
* La temperatura máxima no debe ser superior a 50
* El numero de incidencias no tiene límite
* Las incidencias tiene un nombre que puede ser "frio", "nieve", "lluvia" o "calor"
* Las incidencias tiene una severidad que puede ser "alta", "media" o "baja"
-->
<registro_temperatura 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="./01.temperatura.xsd">

    <provincia>badajoz</provincia>
    <fecha>2021-05-12</fecha>
    <temperatura_minima>40</temperatura_minima>
    <temperatura_maxima>50</temperatura_maxima>
  
    <incidencias>
      <incidencia nombre="frio" severidad="alta"/>
      <incidencia nombre="nieve" severidad="alta"/>
      <incidencia nombre="lluvia" severidad="alta"/>
    </incidencias>
  
  </registro_temperatura>
