=== AngelAcedo12/LMSGI-2223/Bloque1/Tema2/Ejercicios/01.repaso/03.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="articulos">
        
        <xsd:complexType>
            <xsd:choice maxOccurs="4">
                <xsd:element name="monitor" type="tipoMonitor"/>
                <xsd:element name="raton" type="tipoRaton"/>
                <xsd:element name="teclado" type="tipoTeclado"/>
            </xsd:choice>
            <xsd:attribute name="fechageneracion" type="xsd:date"/>
        </xsd:complexType>

    </xsd:element>

    <xsd:complexType name="tipoMonitor">
        <xsd:sequence>
            <xsd:element ref="descripcion"/>
            <xsd:element name="resolucion" type="tipoResolucion"></xsd:element>
        </xsd:sequence>
        <xsd:attribute name="codigo" type="tipoAttCodigo" use="optional" />

    </xsd:complexType>

    <xsd:complexType name="tipoRaton">
        <xsd:sequence>
            <xsd:element ref="descripcion"/>
            <xsd:element name="peso" type="tipoPeso"/>
        </xsd:sequence>
        <xsd:attribute name="codigo" type="tipoAttCodigo" use="optional" />
    </xsd:complexType>

    <xsd:complexType name="tipoTeclado">
        <xsd:sequence>
            <xsd:element ref="descripcion"/>
        </xsd:sequence>
        <xsd:attribute name="codigo" type="tipoAttCodigo" use="optional" />
    </xsd:complexType>

    <xsd:element name="descripcion" type="xsd:string"/>

    <!-- Tipos de Monitor-->
    <xsd:complexType name="tipoResolucion">
        <xsd:sequence>
            <xsd:element name="ancho" type="xsd:positiveInteger"/>
            <xsd:element name="alto" type="xsd:positiveInteger"/>
        </xsd:sequence>
    </xsd:complexType>

    <!-- Tipos de Raton-->
    <xsd:complexType name="tipoPeso">
        <xsd:simpleContent>
            <xsd:extension base="xsd:positiveInteger">
                <xsd:attribute name="unidad" type="tipoAttUnidad"/>
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>

    <!-- Tipo-atributo-codigo-->
    <xsd:simpleType name="tipoAttCodigo">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[A-Z]{3}\-[A-Z]{3}\-[0-9]{3}"></xsd:pattern>
        </xsd:restriction>
    </xsd:simpleType>

    <!-- Tipo-atributo-unidad-->
    <xsd:simpleType name="tipoAttUnidad">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="g"/>
            <xsd:enumeration value="cg"/>
        </xsd:restriction>
    </xsd:simpleType>

</xsd:schema>

=== AngelAcedo12/LMSGI-2223/Bloque1/Tema2/Ejercicios/01.repaso/03.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
Se pide elaborar un esquema que valide un fichero con las siguientes restricciones:

El elemento raíz es articulos. Dicho elemento raíz debe llevar siempre un atributo fechaGeneración.
Dentro de la raíz puede haber uno o varios de cualquiera de los siguientes elementos: monitor, teclado o raton. 
Cualquiera de los tres elementos puede llevar un atributo codigo que tiene siempre la estructura «tres letras, guión, tres letras, guión, tres cifras».
 Además, cualquiera de los tres debe llevar dentro y en primer lugar un elemento descripción que contiene texto.
Un monitor debe llevar (aparte de la descripción que va en primer lugar) un elemento resolución que a su vez debe 
llevar dentro dos elementos y en este orden ancho y alto. Tanto ancho, como alto deben llevar siempre dentro un entero positivo.
Un ratón debe llevar (aparte de la descripción que va en primer lugar).

Además, el peso lleva siempre dentro un atributo unidad que solo puede valer «g» o «cg».
Intentar extraer los tipos o restricciones compartidas mas de una vez. 
Por ejempo, el atributo codigo tiene una restricción y este atributo está presente en Monitor, Raton y Reclado. 
Además también tienen un elemento “descripcion” que está presente en los tres.

-->

<!--Obligatorio el tener fechaGeneracion-->
<articulos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./03.xsd"
fechageneracion="2018-03-01">

    <!--El atributo codigo es optativo siempre-->
    <monitor codigo="AAA-DDD-222">
        <!--Descripcion obligatoria-->
        <descripcion>Monitor de x pulgadas...</descripcion>
        <resolucion>
            <ancho>1920</ancho>
            <alto>1400</alto>
        </resolucion>
    </monitor>
    <raton>
        <!--Descripcion obligatoria-->
        <descripcion>Raton ergonomico...</descripcion>
        <!--La unidad es g o cg-->
        <peso unidad="g">100</peso>
    </raton>
    <teclado codigo="DDD-XXX-111">
        <!---Descripcion obligatoria-->
        <descripcion>Teclado estándar</descripcion>
    </teclado>
    <monitor codigo="CCC-GGG-666">
        <!--Descripcion obligatoria-->
        <descripcion>Monitor de x pulgadas...</descripcion>
        <resolucion>
            <ancho>1400</ancho>
            <alto>1000</alto>
        </resolucion>
    </monitor>
</articulos>
