<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE listaventas [
    <!ELEMENT listaventas (venta)*>
    <!ELEMENT venta (Importe,comprador,vendedor,fecha,codigofactura)*>
    <!ELEMENT Importe (#PCDATA)>
    <!ELEMENT comprador (#PCDATA)>
    <!ELEMENT vendedor (#PCDATA)>
    <!ELEMENT fecha (#PCDATA)>
    <!ELEMENT codigofactura (#PCDATA)>
]>
<listaventas>
  <venta>
    <Importe>1500</Importe>
    <comprador>While E.Coyote</comprador>
    <vendedor>ACME</vendedor>
    <fecha></fecha>
    <codigofactura>E17</codigofactura>
  </venta>
  <venta>
    <Importe>750</Importe>
    <comprador>Elmer Fudd</comprador>
    <vendedor>ACME</vendedor>
    <fecha>18-02-2015</fecha>
    <codigofactura>E18</codigofactura>
  </venta>
</listaventas>