=== AngelAcedo12/LMSGI-2223/Bloque1/Tema2/Ejercicios/01.repaso/07.solucion.dtd
<!ELEMENT factura (emisor,cliente,detalle+)>
    <!ATTLIST factura fecha-emision CDATA #REQUIRED>
    <!ATTLIST factura numero CDATA #REQUIRED>

<!ELEMENT emisor (nombre,CIF,telefono)>
<!ELEMENT cliente (nombre,CIF,telefono)>
<!ELEMENT detalle (linea)+>
    <!ATTLIST detalle importe CDATA #REQUIRED>

<!ELEMENT linea (descripcion,cantidad,oferta?,pvp)>
<!ATTLIST linea codigo-articulo ID #REQUIRED>
<!ATTLIST linea tipo CDATA #IMPLIED>

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT CIF (#PCDATA)>
<!ELEMENT cantidad (#PCDATA)>
<!ELEMENT oferta EMPTY>
<!ELEMENT pvp (#PCDATA)>

=== AngelAcedo12/LMSGI-2223/Bloque1/Tema2/Ejercicios/01.repaso/07.solucion.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE factura SYSTEM "./07.solucion.dtd">
<factura fecha-emision="18/12/2013" numero="27" >
    <emisor>
       <nombre>Librería Perez</nombre>
       <CIF>44555666B</CIF>
       <telefono>7778889999</telefono>
    </emisor>
    <cliente>
        <nombre>Biblioteca Txantrea</nombre>
        <CIF>33111222A</CIF>
        <telefono>333999444</telefono>
    </cliente>
    <detalle importe="85€">
        <linea codigo-articulo="aw7" tipo="Libro">
            <descripcion>Analiltica Web 2.0</descripcion>
            <cantidad>1</cantidad>
            <oferta/>
            <pvp>25€</pvp>
        </linea>
        <linea codigo-articulo="CP5" tipo="DVD">
            <descripcion>Curso de HTML</descripcion>
            <cantidad>2</cantidad>
            <pvp>30€</pvp>
        </linea>
    </detalle>
</factura>
