=== AngelAcedo12/LMSGI-2223/Bloque1/Tema2/Ejercicios/01.repaso/08.solucion.dtd
<!ELEMENT panel-vuelos (aeropuerto,vuelos,fecha_panel)>
<!ELEMENT vuelos (vuelo)+>
<!ELEMENT vuelo (diario?,origen,destino,hora_salida,hora_llegada)>
    <!ATTLIST vuelo codigo CDATA #REQUIRED>
    <!ATTLIST vuelo estado (C|E|R) "E">

<!ELEMENT aeropuerto (#PCDATA)>
<!ELEMENT diario EMPTY>
<!ELEMENT origen (#PCDATA)>
<!ELEMENT destino (#PCDATA)>
<!ELEMENT hora_salida (#PCDATA)>
<!ELEMENT hora_llegada (#PCDATA)>
<!ELEMENT fecha_panel (#PCDATA)>

=== AngelAcedo12/LMSGI-2223/Bloque1/Tema2/Ejercicios/01.repaso/08.solucion.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE panel-vuelos SYSTEM "./08.solucion.dtd">
<panel-vuelos>
    <aeropuerto>JFK</aeropuerto>
    <vuelos>
        <vuelo codigo="V22" estado="R">
            <diario/>
            <origen>New york</origen>
            <destino>Chicago</destino>
            <hora_salida>09:30</hora_salida>
            <hora_llegada>11:30</hora_llegada>
         </vuelo>
         <vuelo codigo="V23" estado="C">
             <origen>New york</origen>
             <destino>Mimami</destino>
             <hora_salida>10:15</hora_salida>
             <hora_llegada>11:15</hora_llegada>
          </vuelo>
    </vuelos>
    <fecha_panel>20/12/2013</fecha_panel>
</panel-vuelos>
